### PR TITLE
fix CTest->Unity on PR template

### PR DESCRIPTION
**Pull request by bernardoaraujor**
# Description of change

PR template mentioned CTest instead of Unity as test framework.

## Type of change

- Bugfix (a non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by oopsmonk** [comment]
I think you mixed up CTest and Unity. CTest is a CMake module. Unity is an unit test framework/library.

**Comment by bernardoaraujor** [comment]
is CTest still used anywhere?

**Comment by oopsmonk** [comment]
> is CTest still used anywhere?

~iota.c uses CTest and Unity.~
iota.c uses CTest as the testing tool and Unity as the testing framework.

**Comment by bernardoaraujor** [comment]
ok my bad, sorry.
closing.

**Pull request closed without merging**
